name: Generate Release Notes

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Generate Release Notes
        uses: your-username/make-release-note@v1
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.number }}
          language: 'ja' 